---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli-deployment
spec:
  selector:
    matchLabels:
      app: aws-cli
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-cli
    spec:
      #serviceAccountName: 
      containers:
      - name: aws-cli
        image: amazon/aws-cli
        command: [ "/bin/bash", "-c", "--" ]  
          #command: ['aws', 's3', 'ls', 's3://xxxx/', '-']
        #args: [ "while true; do sleep 300;date; aws s3 ls s3://xxx/; if [ $? -ne 0 ];then exit;fi; done" ]
        args: [ "while true; do sleep 30; done;" ]
