---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  targetCPUUtilizationPercentage: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: maradwan/myapp:v1
        ports:
        - containerPort: 8888
        #resources:
        #  requests:
        #    cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "env=dev, Name=my-app, cost=2121"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: 10.1.24.137 ,10.1.80.58, 10.1.157.217
    service.beta.kubernetes.io/aws-load-balancer-subnets: private-eu-central-1a, private-eu-central-1b, private-eu-central-1c
spec:
  selector:
    app: myapp
    #    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: LoadBalancer
