defaultNamespace: monitoring

helm:
  chart: grafana
  repo: https://charts.bitnami.com/bitnami
  version: 7.9.8 
  values:
    ingress:
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      enabled: true
      ingressClassName: nginx
      tls: true
      hostname: grafana.apps.gozeit.com
      hosts: 
        - grafana.apps.gozeit.com

      
