defaultNamespace: monitoring

helm:
  chart: grafana
  repo: https://charts.bitnami.com/bitnami
  version: 8.2.20 
  values:
    ingress:
      tls: true
      enabled: true
      ingressClassName: nginx
      hostname: grafana2.apps.gozeit.com
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - grafana2.apps.gozeit.com
        
      extraTls:
      - hosts: 
          - grafana2.apps.gozeit.com
        secretName: grafana-tls-secret
