apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-demo
  namespace: demo
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: demo-app-role
          serviceAccountRef:
            name: vault-demo
      path: backend
      server: http://devops-fleet-vault.vault.svc.cluster.local:8200
      version: v2
