apiVersion: v1
kind: Pod
metadata:
  name: mysql-rds-connection-test
  namespace: default
spec:
  containers:
  - name: mysqlconn
    image: mysql:latest
    command: ['mysql']
    #command: [ "/bin/bash", "-c", "--" ]
    args: [ '-u', '$MYSQL_USER', '-p$MYSQL_PASSWORD' -h '$MYSQL_HOST', '-c', 'show databases;']
    #args: [ "while true; do sleep 30; done;" ]
    env:
    - name: MYSQL_HOST
      valueFrom:
        secretKeyRef:
          name: production-rds-conn-string
          key: endpoint
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: production-rds-conn-string
          key: password
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: production-rds-conn-string
          key: username
    - name: MYSQL_TCP_PORT
      valueFrom:
        secretKeyRef:
          name: production-rds-conn-string
          key: port
