apiVersion: v1
kind: Pod
metadata:
  name: mysql-rds-connection-test
  namespace: default
spec:
  containers:
  - name: mysqlconn
    image: mysql:latest
    command: [ "sh", "-c"]
    args:
      - while true; do
          mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -h $MYSQL_HOST -e 'show databases';
          sleep 10;
      done;
    env:
    - name: MYSQL_HOST
      valueFrom:
        secretKeyRef:
          name: production-rds-conn-string
          key: endpoint
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: production-rds-conn-string
          key: password
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: production-rds-conn-string
          key: username
    - name: MYSQL_TCP_PORT
      valueFrom:
        secretKeyRef:
          name: production-rds-conn-string
          key: port
