---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: maradwan/myapp:v2
        ports:
        - containerPort: 8888
        #resources:
        #  requests:
        #    cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: kube-system
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "env=dev, Name=my-app, cost=2121"
spec:
  selector:
    app: myapp
    #    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: LoadBalancer
