apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  generation: 1
  name: demo-app
  namespace: demo
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: demo-app
    secretKey: regcred
  refreshInterval: 15s
  secretStoreRef:
    kind: SecretStore
    name: vault-demo
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: demo-app
    template:
      data:
        .dockerconfigjson: '{{ .regcred | toString }}'
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson

